name: build

on: push

jobs:
  build:
    name: setup and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: show node version
        run: node -v
      - name: install node modules
        run: npm install
      - name: run test
        run: npm run test
      - name: slack notify
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"worknite ci finished."}' ${{ secrets.SLACK_WEBHOOK_URL }}
