name: build

on: push

jobs:
  build:
    name: setup and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: show node version
        run: node -v
      - name: run test
        run: npm run test
